/**
 * ForgeLocal — Pricing Estimate Model
 *
 * Dynamic pricing generated by the pricing engine from SOW + market signals.
 * Provides transparent price range to the customer before booking.
 */

import mongoose, { Schema, Document, model, models } from "mongoose";
import { schemaOptions } from "./_base";

export interface IPricingBreakdown {
  partsCostPaise: number;
  laborMinPaise: number;
  laborMaxPaise: number;
  travelCostPaise: number;
  platformFeePaise: number;
  taxPaise: number;
  urgencySurchargePaise: number;
}

export interface IPricingEstimate extends Document {
  serviceRequestId: mongoose.Types.ObjectId;
  scopeOfWorkId: mongoose.Types.ObjectId;
  customerId: mongoose.Types.ObjectId;

  // Price range shown to customer
  totalMinPaise: number;
  totalMaxPaise: number;
  totalMidpointPaise: number;

  // Breakdown
  breakdown: IPricingBreakdown;

  // Professional payout (before platform fee)
  professionalPayoutMinPaise: number;
  professionalPayoutMaxPaise: number;
  platformFeePercent: number;

  // Customer authorization limit
  maxAuthorizationPaise: number;

  // Pricing signals used
  signals: {
    geographicMultiplier: number;
    urgencyMultiplier: number;
    professionalAvailabilityScore: number;
    marketDemandScore: number;
    historicalJobsCount: number;
  };

  // Validity
  validUntil: Date;
  isExpired: boolean;

  // Version (if SOW changes, new pricing is generated)
  version: number;

  createdAt: Date;
  updatedAt: Date;
}

const PricingEstimateSchema = new Schema<IPricingEstimate>(
  {
    serviceRequestId: {
      type: Schema.Types.ObjectId,
      ref: "ServiceRequest",
      required: true,
    },
    scopeOfWorkId: {
      type: Schema.Types.ObjectId,
      ref: "ScopeOfWork",
      required: true,
    },
    customerId: {
      type: Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },

    totalMinPaise: { type: Number, required: true, min: 0 },
    totalMaxPaise: { type: Number, required: true, min: 0 },
    totalMidpointPaise: { type: Number, required: true, min: 0 },

    breakdown: {
      partsCostPaise: { type: Number, default: 0 },
      laborMinPaise: { type: Number, default: 0 },
      laborMaxPaise: { type: Number, default: 0 },
      travelCostPaise: { type: Number, default: 0 },
      platformFeePaise: { type: Number, default: 0 },
      taxPaise: { type: Number, default: 0 },
      urgencySurchargePaise: { type: Number, default: 0 },
    },

    professionalPayoutMinPaise: { type: Number, default: 0 },
    professionalPayoutMaxPaise: { type: Number, default: 0 },
    platformFeePercent: { type: Number, default: 15, min: 0, max: 100 },

    maxAuthorizationPaise: { type: Number, required: true, min: 0 },

    signals: {
      geographicMultiplier: { type: Number, default: 1 },
      urgencyMultiplier: { type: Number, default: 1 },
      professionalAvailabilityScore: { type: Number, default: 1 },
      marketDemandScore: { type: Number, default: 1 },
      historicalJobsCount: { type: Number, default: 0 },
    },

    validUntil: { type: Date, required: true },
    isExpired: { type: Boolean, default: false },
    version: { type: Number, default: 1, min: 1 },
  },
  schemaOptions
);

PricingEstimateSchema.index({ serviceRequestId: 1 });
PricingEstimateSchema.index({ validUntil: 1, isExpired: 1 });

export const PricingEstimate =
  models.PricingEstimate ??
  model<IPricingEstimate>("PricingEstimate", PricingEstimateSchema);
export default PricingEstimate;
