/**
 * ForgeLocal — Scope of Work Model
 *
 * Generated by InspectAI from DiagnosticSession findings.
 * The SOW is the shared source of truth for customer, professional,
 * pricing engine, and dispute resolution.
 */

import mongoose, { Schema, Document, model, models } from "mongoose";
import { schemaOptions } from "./_base";

export interface ISOWLineItem {
  description: string;
  type: "labor" | "material" | "travel" | "platform_fee" | "other";
  quantity: number;
  unitPricePaise: number;
  totalPricePaise: number;
  notes?: string;
}

export interface ISOWPart {
  name: string;
  sku?: string;
  quantity: number;
  estimatedUnitCostPaise: number;
  isRequired: boolean;
  notes?: string;
}

export type SOWStatus =
  | "draft"
  | "pending_customer_review"
  | "approved"
  | "rejected"
  | "superseded"; // Replaced by a change order

export interface IScopeOfWork extends Document {
  serviceRequestId: mongoose.Types.ObjectId;
  diagnosticSessionId: mongoose.Types.ObjectId;
  customerId: mongoose.Types.ObjectId;
  version: number;         // Increments with each change order
  parentSowId?: mongoose.Types.ObjectId; // If this is a revision

  // Service Details
  serviceCategoryId: mongoose.Types.ObjectId;
  problemTitle: string;
  problemDescription: string;
  likelyRootCause: string;
  confidence: number; // 0-1

  // Work Items
  lineItems: ISOWLineItem[];
  requiredParts: ISOWPart[];

  // Duration
  estimatedDurationMinutes: { min: number; max: number };

  // Risk & Conditions
  riskFlags: string[];
  conditions: string[];     // e.g., "Price may vary if wall access is required"
  requiresOnSiteConfirmation: boolean;

  // Status
  status: SOWStatus;
  customerApprovedAt?: Date;
  customerRejectedAt?: Date;
  customerRejectionReason?: string;

  // Totals (computed fields)
  subtotalPaise: number;
  taxPaise: number;
  totalPaise: number;

  // AI metadata
  generatedByAiProvider: string;

  createdAt: Date;
  updatedAt: Date;
}

const SOWSchema = new Schema<IScopeOfWork>(
  {
    serviceRequestId: {
      type: Schema.Types.ObjectId,
      ref: "ServiceRequest",
      required: true,
    },
    diagnosticSessionId: {
      type: Schema.Types.ObjectId,
      ref: "DiagnosticSession",
      required: true,
    },
    customerId: {
      type: Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },
    version: { type: Number, default: 1, min: 1 },
    parentSowId: { type: Schema.Types.ObjectId, ref: "ScopeOfWork" },

    serviceCategoryId: {
      type: Schema.Types.ObjectId,
      ref: "ServiceCategory",
      required: true,
    },
    problemTitle: { type: String, required: true, trim: true, maxlength: 300 },
    problemDescription: { type: String, required: true, maxlength: 5000 },
    likelyRootCause: { type: String, required: true, maxlength: 1000 },
    confidence: { type: Number, required: true, min: 0, max: 1 },

    lineItems: [
      {
        description: { type: String, required: true },
        type: {
          type: String,
          enum: ["labor", "material", "travel", "platform_fee", "other"],
          required: true,
        },
        quantity: { type: Number, required: true, min: 0 },
        unitPricePaise: { type: Number, required: true, min: 0 },
        totalPricePaise: { type: Number, required: true, min: 0 },
        notes: String,
      },
    ],
    requiredParts: [
      {
        name: { type: String, required: true },
        sku: String,
        quantity: { type: Number, required: true, min: 0 },
        estimatedUnitCostPaise: { type: Number, required: true, min: 0 },
        isRequired: { type: Boolean, default: true },
        notes: String,
      },
    ],

    estimatedDurationMinutes: {
      min: { type: Number, required: true, min: 0 },
      max: { type: Number, required: true, min: 0 },
    },

    riskFlags: { type: [String], default: [] },
    conditions: { type: [String], default: [] },
    requiresOnSiteConfirmation: { type: Boolean, default: false },

    status: {
      type: String,
      enum: ["draft", "pending_customer_review", "approved", "rejected", "superseded"],
      default: "draft",
    },
    customerApprovedAt: { type: Date },
    customerRejectedAt: { type: Date },
    customerRejectionReason: { type: String, maxlength: 2000 },

    subtotalPaise: { type: Number, required: true, min: 0 },
    taxPaise: { type: Number, default: 0, min: 0 },
    totalPaise: { type: Number, required: true, min: 0 },

    generatedByAiProvider: { type: String, default: "mock" },
  },
  schemaOptions
);

SOWSchema.index({ serviceRequestId: 1, version: -1 });
SOWSchema.index({ customerId: 1, status: 1 });

export const ScopeOfWork =
  models.ScopeOfWork ?? model<IScopeOfWork>("ScopeOfWork", SOWSchema);
export default ScopeOfWork;
